version: '3.8'

networks:
  jenkins:

services:
  jenkins-docker:
    container_name: jenkins-docker
    image: docker:23.0.1-dind
    restart: unless-stopped
    privileged: true
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    environment:
      DOCKER_TLS_CERTDIR: /certs
    networks:
      jenkins:
        aliases: 
          - docker
    ports:
      - 2376:2376
    command: --storage-driver overlay2

  jenkins-blueocean:
    container_name: jenkins-blueocean
    image: myjenkins-blueocean:2.387.1-1
    restart: unless-stopped
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: '1'
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    networks:
      - jenkins
    ports:
      - 8080:8080
      - 50000:50000

volumes:
  jenkins-data:
  jenkins-docker-certs:
